version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: edwin1234
      MYSQL_DATABASE: meeting
      MYSQL_USER: edwin
      MYSQL_PASSWORD: edwin1234
    ports:
      - "6033:6033"
    volumes:
      - ./setup_meeting_db.sql:/docker-entrypoint-initdb.d/setup.sql

  login-service:
    build: ./login-service
    container_name: login-service
    environment:
      DB_HOST: mysql
      DB_USER: edwin
      DB_PASSWORD: edwin1234
      DB_NAME: meeting
      JWT_SECRET: supersecretkey
    ports:
      - "4000:4000"
    depends_on:
      - mysql

  register-service:
    build: ./register-service
    container_name: register-service
    environment:
      DB_HOST: mysql
      DB_USER: edwin
      DB_PASSWORD: edwin1234
      DB_NAME: meeting
    ports:
      - "4001:4001"
    depends_on:
      - mysql

  logout-service:
    build: ./logout-service
    container_name: logout-service
    environment:
      DB_HOST: mysql
      DB_USER: edwin
      DB_PASSWORD: edwin1234
      DB_NAME: meeting
    ports:
      - "4002:4002"
    depends_on:
      - mysql

  frontend-jquery:
    build: ./frontend-jquery
    container_name: frontend-jquery
    ports:
      - "3001:80"
    depends_on:
      - login-service
      - register-service
      - logout-service

  frontend-vue:
    build: ./frontend-vue
    container_name: frontend-vue
    ports:
      - "3002:80"
    depends_on:
      - login-service

volumes:
  mysql_data: